version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: snippetbox
      MYSQL_PASSWORD: snippetbox
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - mysql_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_dev
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
